name: Provenance
favicon: null
layout_spectrum: 1
typography_spectrum: 0.78695
title: Provenance
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#28292b'
    - '#595451'
    - '#eeedeb'
    - '#a8a7a5'
    - '#ce8146'
  brandStrength: 0.5
  lightness: 0.5602718612644821
  saturation: 0.5829440441448241
  rhythmicContrast: 0.40941704623401165
purpose: []
