name: Provenance
favicon: null
layout_spectrum: 0.74614
typography_spectrum: 0.75035
title: Provenance
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#28292b'
    - '#eeedeb'
    - '#a8a7a5'
    - '#b64e16'
    - '#db7b48'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
